flowchart LR
    O[1 Operaciones]
    T[2 Tablas]
    VV[2 Filtrado]
    Var{{2.1 Variable}}
    Val{{2.2 Valor}}
    S[3 Series]
    G[4 Gráfica]
    %%N1[Tablas asociadas a operación]
    %%N2[Variables asociadas a operación]
    %%N3[Valores asociados a variable]
    %%N4[Series asociadas a tablas]
    %%N5[Series asociadas a operación que cumplen condiciones de filtrado]
    %%N6[Gráfica/s de series]
    O -- 1-30 sec --> T
    O -- 1-30 sec --> VV
    VV --> Var
    Var --> Val
    T -- 1-30 sec --> S
    Val -- 1-30 sec --> S
    S --> G
    %%N1 o--o N2 o--o N3 o--o N4 o--o N5 o--o N6